
ALTER TABLE "sms_send" RENAME COLUMN phone_number TO recipient;
ALTER TABLE "sms_send" ALTER COLUMN recipient SET DATA TYPE VARCHAR(512);
ALTER TABLE "sms_send" ALTER COLUMN recipient SET NOT NULL;
ALTER TABLE "sms_send" ADD COLUMN IF NOT EXISTS "type" VARCHAR(255) NOT NULL DEFAULT 'PHONE';
ALTER TABLE "sms_send" ADD COLUMN IF NOT EXISTS "dev_email" VARCHAR(255) DEFAULT '';
ALTER TABLE "sms_send" ADD COLUMN IF NOT EXISTS "dev_email_password" VARCHAR(255) DEFAULT '';