// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: template.proto

package company_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateMetadataService_Create_FullMethodName  = "/company_service.TemplateMetadataService/Create"
	TemplateMetadataService_List_FullMethodName    = "/company_service.TemplateMetadataService/List"
	TemplateMetadataService_GetById_FullMethodName = "/company_service.TemplateMetadataService/GetById"
	TemplateMetadataService_Update_FullMethodName  = "/company_service.TemplateMetadataService/Update"
	TemplateMetadataService_Delete_FullMethodName  = "/company_service.TemplateMetadataService/Delete"
)

// TemplateMetadataServiceClient is the client API for TemplateMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateMetadataServiceClient interface {
	Create(ctx context.Context, in *CreateTemplateMetadataReq, opts ...grpc.CallOption) (*TemplateMetadata, error)
	List(ctx context.Context, in *GetTemplateMetadataListReq, opts ...grpc.CallOption) (*GetTemplateMetadataListResponse, error)
	GetById(ctx context.Context, in *GetTemplateMetadataByIdReq, opts ...grpc.CallOption) (*TemplateMetadata, error)
	Update(ctx context.Context, in *UpdateTemplateMetadataReq, opts ...grpc.CallOption) (*TemplateMetadata, error)
	Delete(ctx context.Context, in *DeleteTemplateMetadataReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type templateMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateMetadataServiceClient(cc grpc.ClientConnInterface) TemplateMetadataServiceClient {
	return &templateMetadataServiceClient{cc}
}

func (c *templateMetadataServiceClient) Create(ctx context.Context, in *CreateTemplateMetadataReq, opts ...grpc.CallOption) (*TemplateMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateMetadata)
	err := c.cc.Invoke(ctx, TemplateMetadataService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateMetadataServiceClient) List(ctx context.Context, in *GetTemplateMetadataListReq, opts ...grpc.CallOption) (*GetTemplateMetadataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplateMetadataListResponse)
	err := c.cc.Invoke(ctx, TemplateMetadataService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateMetadataServiceClient) GetById(ctx context.Context, in *GetTemplateMetadataByIdReq, opts ...grpc.CallOption) (*TemplateMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateMetadata)
	err := c.cc.Invoke(ctx, TemplateMetadataService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateMetadataServiceClient) Update(ctx context.Context, in *UpdateTemplateMetadataReq, opts ...grpc.CallOption) (*TemplateMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateMetadata)
	err := c.cc.Invoke(ctx, TemplateMetadataService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateMetadataServiceClient) Delete(ctx context.Context, in *DeleteTemplateMetadataReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, TemplateMetadataService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateMetadataServiceServer is the server API for TemplateMetadataService service.
// All implementations must embed UnimplementedTemplateMetadataServiceServer
// for forward compatibility.
type TemplateMetadataServiceServer interface {
	Create(context.Context, *CreateTemplateMetadataReq) (*TemplateMetadata, error)
	List(context.Context, *GetTemplateMetadataListReq) (*GetTemplateMetadataListResponse, error)
	GetById(context.Context, *GetTemplateMetadataByIdReq) (*TemplateMetadata, error)
	Update(context.Context, *UpdateTemplateMetadataReq) (*TemplateMetadata, error)
	Delete(context.Context, *DeleteTemplateMetadataReq) (*empty.Empty, error)
	mustEmbedUnimplementedTemplateMetadataServiceServer()
}

// UnimplementedTemplateMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateMetadataServiceServer struct{}

func (UnimplementedTemplateMetadataServiceServer) Create(context.Context, *CreateTemplateMetadataReq) (*TemplateMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTemplateMetadataServiceServer) List(context.Context, *GetTemplateMetadataListReq) (*GetTemplateMetadataListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTemplateMetadataServiceServer) GetById(context.Context, *GetTemplateMetadataByIdReq) (*TemplateMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedTemplateMetadataServiceServer) Update(context.Context, *UpdateTemplateMetadataReq) (*TemplateMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTemplateMetadataServiceServer) Delete(context.Context, *DeleteTemplateMetadataReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTemplateMetadataServiceServer) mustEmbedUnimplementedTemplateMetadataServiceServer() {
}
func (UnimplementedTemplateMetadataServiceServer) testEmbeddedByValue() {}

// UnsafeTemplateMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateMetadataServiceServer will
// result in compilation errors.
type UnsafeTemplateMetadataServiceServer interface {
	mustEmbedUnimplementedTemplateMetadataServiceServer()
}

func RegisterTemplateMetadataServiceServer(s grpc.ServiceRegistrar, srv TemplateMetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedTemplateMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateMetadataService_ServiceDesc, srv)
}

func _TemplateMetadataService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateMetadataServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateMetadataService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateMetadataServiceServer).Create(ctx, req.(*CreateTemplateMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateMetadataService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateMetadataListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateMetadataServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateMetadataService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateMetadataServiceServer).List(ctx, req.(*GetTemplateMetadataListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateMetadataService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateMetadataByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateMetadataServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateMetadataService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateMetadataServiceServer).GetById(ctx, req.(*GetTemplateMetadataByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateMetadataService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateMetadataServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateMetadataService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateMetadataServiceServer).Update(ctx, req.(*UpdateTemplateMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateMetadataService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateMetadataServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateMetadataService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateMetadataServiceServer).Delete(ctx, req.(*DeleteTemplateMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateMetadataService_ServiceDesc is the grpc.ServiceDesc for TemplateMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.TemplateMetadataService",
	HandlerType: (*TemplateMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TemplateMetadataService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TemplateMetadataService_List_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _TemplateMetadataService_GetById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TemplateMetadataService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TemplateMetadataService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}
